apiVersion: v1
kind: Namespace
metadata:
  # annotations:
    # np.rke2.io: resolved
  # creationTimestamp: null
  labels:
    kubernetes.io/metadata.name: argocd
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.23
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.23
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.23
  name: argocd

---
apiVersion: v1
kind: LimitRange
metadata:
  name: argocd-limits
spec:
  limits:
  - defaultRequest:
      cpu: 10m
      memory: 64Mi
    #default:
    #  cpu: 100m
    #  memory: 256Mi
    type: Container