apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/ghost-namespace.yaml
  - resources/ghost-pvc.yaml
  - resources/ghost-deployment.yaml
  - resources/ghost-service.yaml
  - resources/ghost-ingress.yaml

# patchesStrategicMerge:
#   - overlays/y.yaml
#   - overlays/x.yaml

namespace: ghost

images:
- name: ghost
  newTag: "5"
