apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  annotations:
    # you'll want to change the default over time, e.g. when you move to new storage solution,
    # so we recommend you version them from the outset by suffixing the version
    # workflows.argoproj.io/default-artifact-repository: default-v1
    workflows.argoproj.io/default-artifact-repository: s3-plasacloud-v1
data:
  # default-v1: |
  #   archiveLogs: true
  #   s3:
  #     bucket: my-bucket
  #     endpoint: minio:9000
  #     insecure: true
  #     accessKeySecret:
  #       name: my-minio-cred
  #       key: accesskey
  #     secretKeySecret:
  #       name: my-minio-cred
  #       key: secretkey
  # my-key: |
  #   archiveLogs: true
  #   s3:
  #     bucket: my-bucket
  #     endpoint: minio:9000
  #     insecure: true
  #     accessKeySecret:
  #       name: my-minio-cred
  #       key: accesskey
  #     secretKeySecret:
  #       name: my-minio-cred
  #       key: secretkey
  s3-plasacloud-v1: |
    archiveLogs: true
    s3:
      bucket: argo-artifact-repo-v1-b4a64967
      endpoint: minio.plasacloud.de:9000
      insecure: false
      accessKeySecret:
        name: argo-artifact-s3-cred
        key: accesskey
      secretKeySecret:
        name: argo-artifact-s3-cred
        key: secretkey
  empty: ""