apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: ghost-blog-content
   # namespace: ghost
spec:
   accessModes:
   - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi
   storageClassName: local-path
