
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/grafana-namespace.yaml
  - resources/grafana-endpoint.yaml
  - resources/grafana-service.yaml
  - resources/grafana-ingress.yaml

# patchesStrategicMerge:
#   - overlays/y.yaml
#   - overlays/x.yaml

namespace: grafana-external
