apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: n8n
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: n8n
  version: 0.5.0
  repo: https://8gears.container-registry.com/chartrepo/library/

# patchesStrategicMerge:
#   - overlays/y.yaml
#   - overlays/x.yaml
# commonLabels:
#   app.kubernetes.io/managed-by: ArgoCD

namespace: n8n

# images:
# - name: n8nio/n8n
#   newTag: "0.209.2"
