# n8n:
#   encryption_key: #echo -n "key" | base64
config:
  host: n8n.plasa.cloud
  editorBaseUrl: https://n8n.plasa.cloud
  generic:
    timezone: Europe/Berlin
  endpoints:
    payloadSizeMax: 100
  database:
    type: sqlite
  security: 
    basicAuth:
      active: false
      user: n8n
      hash: true
      password: "n8n:$2y$05$9aZABvWOYB/kz0Ioz4MJuesmgsncZ5DGtBi65PgBhCqbPRzwOJmA6" # htpasswd -B -n
persistence:
  enabled: true
  type: dynamic
  storageClass: "local-path"
  annotations:
    helm.sh/resource-policy: keep
  accessModes:
    - ReadWriteOnce
  size: 5Gi

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    #cert-manager.io/cluster-issuer: http-lets-encrypt
  hosts:
    - host: n8n.plasa.cloud
      paths:
        - "/"
          # pathType: Prefix
  tls:
   - secretName: star-plasa-cloud-tls
     hosts:
       - n8n.plasa.cloud

resources:
  limits:
    #cpu: 2000m
    memory: 4096Mi
  requests:
    cpu: 100m
    memory: 128Mi

image:
  repository: n8nio/n8n
  pullPolicy: IfNotPresent
  tag: "0.209.2"