apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- base/argo-cd-namespace.yaml
#- base/argo-cd-certificate.yaml
- base/argo-cd-ui-ingress.yaml
# - base/rollouts-extension.yaml
# - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml
# - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.4
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml

# components:
# - https://github.com/argoproj-labs/argocd-extensions/manifests

patchesStrategicMerge:
- overlays/argo-cd-cm.yaml
- overlays/argocd-server-service.yaml
# - overlays/argocd-repo-server-deploy.yaml
# - overlays/argocd-notifications-controller-deploy.yaml
# - overlays/argocd-notifications-cm.yaml
# - https://raw.githubusercontent.com/argoproj/argo-cd/master/notifications_catalog/install.yaml


patchesJson6902:
- path: overlays/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocd

commonLabels:
  app: argocd

images:
- name: quay.io/argoproj/argocd
  #newName: ghcr.io/argoproj/argocd
  newTag: v2.5.4
